apiVersion: apps/v1
kind: Deployment
metadata:
  name: adcash-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adcash-webapp
  template:
    metadata:
      labels:
        app: adcash-webapp
    spec:
      containers:
        - name: adcash-webapp-container
          image: drcemae/demo-adcash.webapp:0.0.4
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"