apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: adcash-webapp
  region: eu-west-1

nodeGroups:
  - name: adcash-nodes
    instanceType: t3.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    volumeSize: 20