apiVersion: apps/v1
kind: Deployment
metadata:
  name: adcash-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adcash-webapp
  template:
    metadata:
      labels:
        app: adcash-webapp
    spec:
      containers:
        - name: adcash-webapp-container
          image: drcemae/adcash.webapp:0.0.4
          ports:
            - containerPort: 80


